server:
  port: 8002
spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #192.168.15.129 MySQL5.7版本 密码root 要加上&useSSL=false MySQL8.0可以不加
    url: jdbc:mysql://192.168.15.129:3306/seckill?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: hikaricp
      # 最小空闲连接
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（默认十分钟）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0：表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  # redis配置
  redis:
    host: 192.168.15.129
    port: 6379
    password: zzp
    # 操作的数据库（默认0库）
    database: 0
    # 超时时间（ms）
    timeout: 10000

    lettuce:
      pool:
        # 最大连接数
        max-active: 20
        # 最大连接阻塞等待时间，默认-1（负数表示没有限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.zzp.seckilldemo.entity

# mybatis sql 打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.zzp.seckilldemo.mapper: debug